import com.google.gms.googleservices.GoogleServicesPlugin.MissingGoogleServicesStrategy

plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.kotlin.compose)
  alias(libs.plugins.google.devtools.ksp)
  alias(libs.plugins.roborazzi)
  alias(libs.plugins.secrets)
  alias(libs.plugins.google.services)
  alias(libs.plugins.firebase.crashlytics.plugin)
}

android {
  namespace = "com.example"
  compileSdk { version = release(36) { minorApiLevel = 1 } }

  defaultConfig {
    applicationId = "com.aistudio.financemanager.qzkp"
    minSdk = 24
    targetSdk = 36
    versionCode = 1
    versionName = "1.0"

    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
  }

  // Release signing is sourced ONLY from environment variables (CI secrets / local shell env).
  // No keystore path defaults to a file in the repo, and no passwords are ever hardcoded here.
  // Required when assembling/bundling a release build:
  //   KEYSTORE_PATH     - absolute path to the upload keystore (decoded from a CI secret; never committed)
  //   KEYSTORE_PASSWORD - store password
  //   KEY_ALIAS         - key alias inside the keystore
  //   KEY_PASSWORD      - key password
  val releaseKeystorePath = System.getenv("KEYSTORE_PATH")
  val releaseStorePassword = System.getenv("KEYSTORE_PASSWORD")
  val releaseKeyAlias = System.getenv("KEY_ALIAS")
  val releaseKeyPassword = System.getenv("KEY_PASSWORD")
  val hasReleaseSigningEnv = !releaseKeystorePath.isNullOrBlank() &&
    !releaseStorePassword.isNullOrBlank() &&
    !releaseKeyAlias.isNullOrBlank() &&
    !releaseKeyPassword.isNullOrBlank()

  // The Crashlytics Gradle plugin's mapping-file upload task requires an appId file that's only
  // generated by the google-services plugin from a real google-services.json. Without one, that
  // task fails build configuration validation ("Input file does not exist") even though
  // googleServices.missingGoogleServicesStrategy = WARN (below) lets the rest of the build proceed.
  // Gate the upload on the file actually being present so local/dev release builds don't need it.
  val hasGoogleServicesJson = file("google-services.json").exists()

  // Debug signing is intentionally NOT overridden here: AGP's built-in "debug" signingConfig
  // auto-generates and reuses a keystore at ~/.android/debug.keystore with well-known credentials
  // the first time it's needed, on every machine, with zero setup. An earlier version of this
  // config pointed debug signing at a project-local "${rootDir}/debug.keystore" file - which is
  // (correctly) gitignored, so it never exists on a fresh checkout, and AGP does NOT auto-generate
  // a keystore at a custom path - only at its own default location. That mismatch broke every
  // fresh clone's debug build (validateSigningDebug: "Keystore file ... not found").
  signingConfigs {
    if (hasReleaseSigningEnv) {
      create("release") {
        storeFile = file(releaseKeystorePath!!)
        storePassword = releaseStorePassword
        keyAlias = releaseKeyAlias
        keyPassword = releaseKeyPassword
      }
    }
  }

  buildTypes {
    release {
      isMinifyEnabled = true
      isShrinkResources = true
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
      // Falls back to the automatic debug signing config for local/dev builds where release
      // secrets aren't present. A real Play Store release MUST run in an environment (CI) that
      // supplies the KEYSTORE_* env vars above; otherwise this intentionally produces a
      // debug-signed (non-uploadable) build.
      signingConfig = if (hasReleaseSigningEnv) {
        signingConfigs.getByName("release")
      } else {
        logger.warn(
          "Release signing env vars (KEYSTORE_PATH/KEYSTORE_PASSWORD/KEY_ALIAS/KEY_PASSWORD) are not " +
            "set - falling back to debug signing. This build CANNOT be uploaded to Play Store."
        )
        signingConfigs.getByName("debug")
      }
      firebaseCrashlytics {
        mappingFileUploadEnabled = hasGoogleServicesJson
      }
    }
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }
  buildFeatures {
    compose = true
    buildConfig = true
    viewBinding = true
  }
  testOptions { unitTests { isIncludeAndroidResources = true } }
}

// Configure the Secrets Gradle Plugin to use .env and .env.example files
// to match the convention used in Web projects.
secrets {
  propertiesFileName = ".env"
  defaultPropertiesFileName = ".env.example"
}

// WARN (not ERROR) so local/dev builds work without a google-services.json. This means Crashlytics
// silently becomes a no-op if the file is absent - CI's release workflow supplies a real
// google-services.json from a secret specifically so production builds do report crashes.
googleServices { missingGoogleServicesStrategy = MissingGoogleServicesStrategy.WARN }

// Some unused dependencies are commented out below instead of being removed.
// This makes it easy to add them back in the future if needed.
dependencies {
  implementation(platform(libs.androidx.compose.bom))
  implementation(platform(libs.firebase.bom))
  implementation("com.google.android.material:material:1.12.0")
  implementation("androidx.appcompat:appcompat:1.7.0")
  implementation("androidx.recyclerview:recyclerview:1.4.0")
  implementation("androidx.cardview:cardview:1.0.0")
  implementation("androidx.activity:activity-ktx:1.10.1")
  // implementation(libs.accompanist.permissions)
  implementation(libs.androidx.activity.compose)
  // implementation(libs.androidx.camera.camera2)
  // implementation(libs.androidx.camera.core)
  // implementation(libs.androidx.camera.lifecycle)
  // implementation(libs.androidx.camera.view)
  implementation(libs.androidx.compose.material.icons.core)
  implementation(libs.androidx.compose.material.icons.extended)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.ui)
  implementation(libs.androidx.compose.ui.graphics)
  implementation(libs.androidx.compose.ui.tooling.preview)
  implementation(libs.androidx.core.ktx)
  // implementation(libs.androidx.datastore.preferences)
  implementation(libs.androidx.lifecycle.runtime.compose)
  implementation(libs.androidx.lifecycle.runtime.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.compose)
  // implementation(libs.androidx.navigation.compose)
  implementation(libs.androidx.room.ktx)
  implementation(libs.androidx.room.runtime)
  implementation(libs.coil.compose)
  implementation(libs.converter.moshi)
  // Crashlytics: the only Firebase product actually used by the app, for production crash/error
  // reporting (see com.example.logging.CrashReporter). firebase-ai and firebase-appcheck-recaptcha
  // were declared but never referenced anywhere in the codebase, so they were removed as dead
  // weight rather than kept "in case" - re-add them if a feature actually needs them.
  implementation(libs.firebase.crashlytics)
  implementation(libs.firebase.analytics)
  // Uncomment to use Firestore:
  // implementation(libs.firebase.firestore)

  // Uncomment ALL FOUR of the following dependencies together to use Firebase Auth and Google
  // Sign-In via Credential Manager:
  // implementation(libs.firebase.auth)
  // implementation(libs.androidx.credentials)
  // implementation(libs.androidx.credentials.play.services)
  // implementation(libs.googleid)
  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core)
  implementation(libs.logging.interceptor)
  implementation(libs.moshi.kotlin)
  implementation(libs.okhttp)
  // implementation(libs.play.services.location)
  implementation(libs.retrofit)
  testImplementation(libs.androidx.compose.ui.test.junit4)
  testImplementation(libs.androidx.core)
  testImplementation(libs.androidx.junit)
  testImplementation(libs.junit)
  testImplementation(libs.kotlinx.coroutines.test)
  testImplementation(libs.robolectric)
  testImplementation(libs.roborazzi)
  testImplementation(libs.roborazzi.compose)
  testImplementation(libs.roborazzi.junit.rule)
  androidTestImplementation(platform(libs.androidx.compose.bom))
  androidTestImplementation(libs.androidx.compose.ui.test.junit4)
  androidTestImplementation(libs.androidx.espresso.core)
  androidTestImplementation(libs.androidx.junit)
  androidTestImplementation(libs.androidx.runner)
  debugImplementation(libs.androidx.compose.ui.test.manifest)
  debugImplementation(libs.androidx.compose.ui.tooling)
  "ksp"(libs.androidx.room.compiler)
  "ksp"(libs.moshi.kotlin.codegen)
}
